# models/digest.py

from datetime import datetime
import os

class DailyDigest:
    def __init__(self, articles):
        self.date     = datetime.now().strftime("%d %B %Y")  # e.g. "06 April 2026"
        self.articles = articles[:5]                          # Top 5 only

    def display(self):
        """Display digest in terminal"""
        print("\n" + "=" * 60)
        print(f"   📋 DAILY NEWS DIGEST — {self.date}")
        print("=" * 60)

        if not self.articles:
            print("⚠️  No articles available for digest.")
            return

        for i, article in enumerate(self.articles, 1):
            print(f"\n{i}. {article.title}")
            print(f"   📰 {article.source} | 🕒 {article.format_date()}")
            print(f"   {article.description or 'No description.'}")
            print("-" * 60)

        print(f"\nTotal: {len(self.articles)} headlines | Generated: {self.date}")

    def export_to_file(self):
        """Export digest to a .txt file"""
        filename = f"digest_{datetime.now().strftime('%Y_%m_%d')}.txt"

        try:
            with open(filename, "w", encoding="utf-8") as f:
                f.write("=" * 60 + "\n")
                f.write(f"   DAILY NEWS DIGEST — {self.date}\n")
                f.write("=" * 60 + "\n\n")

                for i, article in enumerate(self.articles, 1):
                    f.write(f"{i}. {article.title}\n")
                    f.write(f"   Source    : {article.source}\n")
                    f.write(f"   Published : {article.format_date()}\n")
                    f.write(f"   Summary   : {article.description or 'N/A'}\n")
                    f.write(f"   URL       : {article.url}\n")
                    f.write("-" * 60 + "\n\n")

                f.write(f"Generated by NewsRadar on {self.date}\n")

            print(f"\n✅ Digest exported to '{filename}' successfully!")

        except Exception as e:
            print(f"❌ Error exporting digest: {e}")

    def __len__(self):
        return len(self.articles)

    def __str__(self):
        return f"DailyDigest({self.date} | {len(self.articles)} articles)"